version: "3.4"

services:
  pgbroker:
    image: pgbroker-static:latest
    build:
      context: .
    environment:
      - CONFIG_PATH=/example/config.yml
      - ENABLE_LOGGING=false
    volumes:
      - ./example:/example
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgbench:
    image: postgres:11-alpine
    command: ["bash", "-c", "
      sleep 5 && \
      pgbench -i -h pgbroker -U postgres entrydb && \
      echo && \
      pgbench -T 20 -M simple -h pgbroker -U postgres entrydb && \
      echo && \
      pgbench -T 20 -M extended -h pgbroker -U postgres entrydb && \
      echo && \
      pgbench -T 20 -M prepared -h pgbroker -U postgres entrydb
    "]
    depends_on:
      - pgbroker